services:
  pgadmin:
    image: dpage/pgadmin4:9.10
    container_name: pgadmin-obywatel_app
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - app-network

  postgres:
    image: postgres:18.1-alpine
    container_name: auth-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  postgres_citizen_docs:
    image: postgres:18.1-alpine
    container_name: citizen-docs-database
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${CITIZEN_DOCS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CITIZEN_DOCS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CITIZEN_DOCS_POSTGRES_DB}
    volumes:
      - pg_citizen_docs_data:/var/lib/postgresql/data
    networks:
      - app-network

  postgres_notification:
    image: postgres:18.1-alpine
    container_name: notification-database
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${NOTIFICATION_POSTGRES_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_POSTGRES_PASSWORD}
      POSTGRES_DB: ${NOTIFICATION_POSTGRES_DB}
    volumes:
      - pg_notification_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:8.4-alpine
    container_name: auth-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  pg_data:
  redis_data:
  pg_citizen_docs_data:
  pg_notification_data:

networks:
  app-network:
    driver: bridge
